image: python:3.7.3

stages:
    - lint
    - security-check
    - test
    - build

before_script:
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install poetry
    - poetry update

lint:
    stage: lint
    script:
        - poetry run mypy borca
        - poetry run black borca

security-check:
    stage: security-check
    script:
        - poetry run bandit -r borca

test:
    stage: test
    script:
        - poetry run pytest

build:
    stage: build
    only:
        - /^release/.*$/@AndrewSpittlemeister/borca
    script:
        - poetry build --format wheel
        - cp dist/sample_package-*.whl .
    artifacts:
        paths:
            - sample_package-*.whl
