[tool.poetry]
name = "borca"
version = "0.1.0"
description = ""
authors = ["Andrew Spittlemeister <andrew.spittlemeister@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "=0.10.0"

[tool.poetry.dev-dependencies]
pytest = "=5.0.0"
mypy = "=0.711"
bandit = "=1.6.2"
black = "=19.3b0"

[tool.black]
# poetry run black --config pyproject.toml borca
check = true
verbose = true
line-length = 120
diff = true
skip-string-normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[mypy]
# poetry run mypy --config-file=pyproject.toml borca
python_version = 3.7
verbosity = 0
warn_unused_configs = true
show_column_numbers = true

[mypy-sample_package]
warn_return_any = true

[pytest]
# poetry run pytest -c pyproject.toml
testpaths = "tests"
verbose = true
